version: '3'
services:
  tf:
    container_name: angelawhite
    environment:
      - "DISPLAY=${IP}:0"
      - QT_X11_NO_MITSHM=1
      - SHELL=/bin/bash
      - COLUMNS=150
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/app
      - .:/notebooks
